#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#  Copyright (c) 2024.

name: "Setup base"
description: ''

inputs:
  os:
    required: true
    description: ''
  arch:
    required: true
    description: ''
  cache-key:
    required: true
    description: ''
  restore-key:
    required: true
    description: ''
  python-version:
    required: false
    description: ''
    default: '3.12'

outputs:
  cache-dir:
    description: ''
    value: ${{ steps.canonicalize-cache-dir.outputs.cache-dir }}

runs:
  using: "composite"
  steps:
    - name: "Set unified TZ"
      uses: szenius/set-timezone@v2.0
      with:
        # this is an arbitrary choice
        timezoneLinux: "Asia/Singapore"
        timezoneMacos: "Asia/Singapore"
        timezoneWindows: "Singapore Standard Time"

    # notes for next time i bash my head against this:
    # 1. github.workspace and $GITHUB_WORKSPACE are different between container actions and non-container actions
    # 2. action/save-restore claims it expands ~ but that's a lie
    # 3. macos root (/) is read only
    # 4. you have to use windows style paths on windows even though we set shell: bash because
    #    `with: path: ....` is not executed in our chosen shell (and so findind the dir will fail)
    # 5. action/save-restore will tell you there's no cache matching the key when the paths differ
    #    (even if the cache key does exist)
    # 6. on almalinux8, ccache distribution is very old
    # 7. action/save-restore needs a subdir in the cached dir (that's why CCACHE_DIR=.container-cache/ccache)
    - name: "Canonicalize cache dir"
      id: canonicalize-cache-dir
      shell: bash
      run: |
        if [[ "${{ inputs.os }}" == "almalinux" ]] || [[ "${{ inputs.os }}" == "ubuntu" ]]; then
          echo "cache-dir=/tmp/.container-cache" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.os }}" == "macos" ]]; then
          echo "cache-dir=/tmp/.container-cache" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.os }}" == "windows" ]]; then
          echo "cache-dir=D:\a\.container-cache" >> $GITHUB_OUTPUT
        fi

    - name: "Restore cache"
      uses: actions/cache/restore@v3
      with:
        path: ${{ steps.canonicalize-cache-dir.outputs.cache-dir }}
        key:  ${{ inputs.cache-key }}
        restore-keys: ${{ inputs.restore-key }}

    - name: "Install OS deps"
      shell: bash
      run: |
        if [[ "${{ inputs.os }}" == "almalinux" ]]; then
          dnf install -y epel-release 
          dnf install -y sudo ncurses-compat-libs tmate python3-pip git
          # install ccache
          curl -sLO https://github.com/ccache/ccache/releases/download/v4.10.2/ccache-4.10.2-linux-x86_64.tar.xz
          tar -xf ccache-4.10.2-linux-x86_64.tar.xz
          pushd ccache-4.10.2-linux-x86_64 && make install && popd
          # install gh-cli
          curl -sLO https://github.com/cli/cli/releases/download/v2.61.0/gh_2.61.0_linux_amd64.rpm
          rpm -i gh_2.61.0_linux_amd64.rpm
          # lol: failed to run git: fatal: detected dubious ownership in repository at '/__w/eudsl/eudsl'
          git config --global --add safe.directory /__w/eudsl/eudsl
        elif [[ "${{ inputs.os }}" == macos* ]]; then
          brew install ccache ninja
        fi

    - name: "Install Python"
      uses: actions/setup-python@v4
      if: ${{ startsWith(inputs.os, 'macos') || startsWith(inputs.os, 'windows') || startsWith(inputs.os, 'ubuntu') }}
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Setup compiler/toolchain"
      uses: aminya/setup-cpp@v1
      if: ${{ startsWith(inputs.os, 'almalinux') || startsWith(inputs.os, 'ubuntu') || startsWith(inputs.os, 'windows') }}
      with:
        compiler: ${{ startsWith(inputs.os, 'almalinux') && 'gcc' || 'llvm-18' }}
        cmake: true
        ninja: true
        ccache: ${{ startsWith(inputs.os, 'windows') || startsWith(inputs.os, 'ubuntu') }}
        vcvarsall: ${{ startsWith(inputs.os, 'windows') }}

    - name: "Set CC/CXX"
      shell: bash
      run: |
        if [[ "${{ inputs.os }}" == "almalinux" ]]; then
          echo "CC=/opt/rh/gcc-toolset-14/root/usr/bin/gcc" >> $GITHUB_ENV
          echo "CXX=/opt/rh/gcc-toolset-14/root/usr/bin/g++" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "ubuntu" ]]; then
          echo "CC=/usr/lib/llvm-18/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/lib/llvm-18/bin/clang++" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "windows" ]]; then
          echo "CC=/C/Users/runneradmin/llvm/bin/clang-cl.exe" >> $GITHUB_ENV
          echo "CXX=/C/Users/runneradmin/llvm/bin/clang-cl.exe" >> $GITHUB_ENV
        elif [[ "${{ inputs.os }}" == "macos" ]]; then
          echo "CC=/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV
        fi

    - name: "Python deps"
      shell: bash
      run: |
        python3_command=""
        if (command -v python${{ inputs.python-version }} &> /dev/null); then
          python3_command="python${{ inputs.python-version }}"
        elif (command -v python3 &> /dev/null); then
          python3_command="python3"
        elif (command -v python &> /dev/null); then
          python3_command="python"
        fi 
        echo "python3_command=$python3_command" >> $GITHUB_ENV

    - name: "Set CMake/ccache env vars"
      shell: bash
      run: |
        echo "CCACHE_DIR=${{ steps.canonicalize-cache-dir.outputs.cache-dir }}/ccache" >> $GITHUB_ENV
        echo "CCACHE_COMPILERCHECK=string:$($CC --version | head -n 1)" >> $GITHUB_ENV
        echo $CCACHE_COMPILERCHECK
        echo "CCACHE_MAXSIZE=700M" >> $GITHUB_ENV
        echo "CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime,time_macros" >> $GITHUB_ENV
        echo "CCACHE_CPP2=true" >> $GITHUB_ENV
        echo "CCACHE_UMASK=002" >> $GITHUB_ENV
        
        ccache -z

        echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
        echo "Python3_EXECUTABLE=$(which $python3_command)" >> $GITHUB_ENV
