//===-- TritonOps.td - Python bindings for triton --*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===---------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_TRITON_NVIDIA_GPU_OPS
#define PYTHON_BINDINGS_TRITON_NVIDIA_GPU_OPS

include "triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td"

#endif
