name: "Build Triton Upstream bindings wheel"

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  PIP_FIND_LINKS: "https://github.com/llvm/eudsl/releases/expanded_assets/dev https://github.com/makslevental/mlir-wheels/releases/expanded_assets/latest"

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-22.04", "macos-14", "macos-13"]
        python-version: ["3.10", "3.11", "3.12"]
        include: [
          # {runs-on: "ubuntu-22.04", name: "manylinux_x86_64", os: "almalinux", arch: x86_64, container: "quay.io/pypa/manylinux_2_28_x86_64"},
          {runs-on: "ubuntu-22.04", name: "ubuntu_x86_64", os: "ubuntu", arch: x86_64},
          {runs-on: "macos-14", name: "macos_arm64", os: "macos", arch: arm64},
          {runs-on: "macos-13", name: "macos_x86_64", os: "macos", arch: x86_64},
        ]
          # triton doesn't distribute a windows build of llvm...
          # - name: "windows_x86_64"
          #   runs-on: "windows-2019"
          #   os: "windows"
          #   arch: x86_64

    runs-on: ${{ matrix.runs-on }}

    name: "${{ matrix.name }} ${{ matrix.python-version }}"

    defaults:
      run:
        shell: bash

    permissions:
      id-token: write
      contents: write

    env:
      # either the PR number or `branch-N` where N always increments
      cache-key: "triton_mlir_${{ matrix.name }}_${{ matrix.python-version }}_${{ format('{0}-{1}', github.ref_name, github.run_number) }}"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: "Setup base"
        uses: ./.github/actions/setup_base
        id: setup_base
        with:
          cache-key: ${{ env.cache-key }}
          restore-key: "triton_mlir_${{ matrix.name }}_${{ matrix.python-version }}_"
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}

      - if: ${{ matrix.os == 'almalinux' }}
        run: |
          git config --global --add safe.directory /__w/triton/triton

      - name: "Build"
        run: |
          
          set -x
          
          pushd python/triton_mlir
          $python3_command -m pip install setuptools wheel
          $python3_command -m pip install -r requirements.txt
          LLVM_URL="$($python3_command setup.py --llvm-url)" 
          popd
          
          # curl -sLO $LLVM_URL
          # LLVM_NAME=$(basename "$LLVM_URL" ".tar.gz")
          # tar xf $LLVM_NAME.tar.gz
          # export LLVM_INSTALL_DIR="$PWD/$LLVM_NAME"

          pip -q download circt -f https://github.com/makslevental/circt/releases/expanded_assets/latest --no-deps
          unzip -q circt*whl -d circt-install
          export LLVM_INSTALL_DIR="$PWD/circt-install"
          export TRITON_SRC_DIR="$PWD"
          export TRITON_BUILD_DIR="$PWD/triton-build"
          export TRITON_INSTALL_DIR="$PWD/triton-install/triton-install"
          
          ccache -z
          
          cmake_options=(
            -S "$TRITON_SRC_DIR"
            -B "$TRITON_BUILD_DIR"
            
            -DCMAKE_BUILD_TYPE=TritonRelBuildWithAsserts 
            -DCMAKE_PREFIX_PATH="$LLVM_INSTALL_DIR" 
            -DCMAKE_INSTALL_PREFIX="$TRITON_INSTALL_DIR" 
           
            -DCMAKE_C_VISIBILITY_PRESET=hidden 
            -DCMAKE_CXX_VISIBILITY_PRESET=hidden 
            -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON 
          
            -DPython3_EXECUTABLE="$(which $python3_command)"
          
            # on AddLLVM.cmake has `PRE_BUILD` in it 
            -DCMAKE_POLICY_DEFAULT_CMP0175=OLD
        
            -DTRITON_CODEGEN_BACKENDS="amd;nvidia" 
            -DTRITON_BUILD_MLIR_PYTHON_MODULE=ON 
            -DTRITON_BUILD_PROTON=OFF 
            -DTRITON_BUILD_PYTHON_MODULE=OFF 
            -DTRITON_BUILD_TUTORIALS=OFF 
            -DTRITON_BUILD_UT=OFF
          )
          
          if [[ "${{ matrix.os }}" == "ubuntu" ]] || [[ "${{ matrix.os }}" == "almalinux" ]]; then
              cmake_options+=(
                -DCMAKE_EXE_LINKER_FLAGS_INIT="-fuse-ld=lld-18"
                -DCMAKE_SHARED_LINKER_FLAGS_INIT="-fuse-ld=lld-18"
                -DCMAKE_MODULE_LINKER_FLAGS_INIT="-fuse-ld=lld-18"
              )
          fi
          
          # don't build a fat binary
          if [[ "${{ matrix.os }}" == "macos" ]]; then
              cmake_options+=(
                -DCMAKE_MODULE_LINKER_FLAGS="-Wl,-U -Wl,_PyClassMethod_New"
                -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} 
              )
          fi
          
          cmake "${cmake_options[@]}"
          cmake --build "$TRITON_BUILD_DIR" --target TritonPythonModules
          
          ccache -s
          
          # prevent universal wheels from being built for macos
          if [[ "${{ matrix.os }}" == "macos" ]]; then
            _PYTHON_HOST_PLATFORM=$($python3_command -c "import sysconfig; print(sysconfig.get_platform())")
            export _PYTHON_HOST_PLATFORM=$(echo $_PYTHON_HOST_PLATFORM | sed 's/universal2/${{ matrix.arch }}/g')
          fi
          
          pushd "$TRITON_SRC_DIR/python/triton_mlir"
          $python3_command -m pip wheel . -w "$TRITON_SRC_DIR/wheelhouse"
          popd

      - name: "Test"
        run: |
          
          $python3_command -m pip install pytest mlir-native-tools triton-mlir -f $PWD/wheelhouse
          $python3_command -m pytest -s python/triton_mlir/test

      - name: "Test HIP"
        if: ${{ matrix.os != 'macos' }}
        run: |
          
          $python3_command -m pip install hip-python -i https://test.pypi.org/simple

      - name: Upload artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: triton_mlir_${{ matrix.name }}_${{ matrix.python-version }}_artifact
          path: wheelhouse
          if-no-files-found: warn

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "wheelhouse/triton_mlir*.whl"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          name: "latest"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          omitBody: true

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          owner: makslevental
          repo: wheels
          artifacts: "wheelhouse/triton_mlir*.whl"
          token: "${{ secrets.WHEELS_RELEASE }}"
          tag: "i"
          name: "i"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          omitBody: true
          artifactErrorsFailBuild: true

      - name: "Save cache"
        uses: actions/cache/save@v4.2.0
        if: ${{ !cancelled() }}
        with:
          path: ${{ steps.setup_base.outputs.cache-dir }}
          key: ${{ env.cache-key }}
